###
POST http://localhost:8080/sell/save
Content-Type: application/json

{
  "code": "code 1",
  "name": "name 1"
}

###
POST http://localhost:8080/sell/update
Content-Type: application/json

{
  "id": "992d7378-b070-4198-b7f1-ab9db37241bc",
  "code": "code 10",
  "name": "name 10"
}

###
POST http://localhost:8080/sell/delete
Content-Type: application/json

{
  "id": "992d7378-b070-4198-b7f1-ab9db37241bc"
}

###
POST http://localhost:8080/sell/search
Content-Type: application/json

{
  "idList": [
    "992d7378-b070-4198-b7f1-ab9db37241bc"
  ],
  "page": 0,
  "size": 10
}

